default:
  http_metas:
    content-type: text/html

  metas:
    title:        Exchange
    robots:       index, follow
    description:  exchange is a place to share themes, applications and modules for the enlightenment shell 
    keywords:     enlightenment, exchange, wallpaper, background, theme, application, efl, module, emodules, e_modules
    language:     en

  stylesheets:    [main, ReMooz, ratings]

  javascripts:    [mootools, mootools-more, ReMooz, ratings, script]

  has_layout:     on
  layout:         layout
